# Generated by Django 3.1.8 on 2021-11-21 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_db', '0002_auto_20210815_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explanation',
            name='excerpt',
        ),
    ]
