# Generated by Django 3.1.8 on 2021-08-15 05:02

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('username', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Last Name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Join Date')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is the User a Staff?')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is the User Active?')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is the Teacher Verified?')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Is the User Blocked?')),
                ('account_type', models.PositiveSmallIntegerField(choices=[(1, 'Student'), (2, 'Teacher'), (3, 'Content Creator'), (4, 'Manager'), (5, 'Admin')], default=1, verbose_name='Account Type')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_public', models.BooleanField(default=True, verbose_name='Is the profile public or private?')),
                ('profile_pic', imagekit.models.fields.ProcessedImageField(blank=True, default='profiles/avatar.png', null=True, upload_to=accounts.models.upload_to_path)),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (3, 'Other'), (4, 'Prefer Not to Answer')], null=True, verbose_name='Gender')),
                ('pronouns', models.CharField(blank=True, max_length=30, null=True, verbose_name='Pronouns')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Last Logged-in')),
                ('user_rep', models.IntegerField(default=0, verbose_name='User Reputation')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='State')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Country')),
                ('name_of_institution', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Institution')),
                ('phone_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone Number')),
                ('email_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact Email Address')),
                ('website_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Website URL')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
