# Generated by Django 3.1.7 on 2021-03-31 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('user_name', models.CharField(max_length=50, unique=True, verbose_name='Username')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='Full Name')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Join Date')),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (3, 'Other'), (4, 'Prefer Not to Answer')], null=True, verbose_name='Gender')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Last Logged-in')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is the User a Staff?')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is the User Active?')),
                ('is_public', models.BooleanField(default=True, verbose_name='Is the profile public or private?')),
                ('account_type', models.PositiveSmallIntegerField(choices=[(1, 'Student'), (2, 'Teacher'), (3, 'Content Creator'), (4, 'Manager'), (5, 'Admin')], default=1, verbose_name='Account Type')),
                ('name_of_institution', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Institution')),
                ('phone_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone Number')),
                ('email_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact Email Address')),
                ('website_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Website URL')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
    ]
