# Generated by Django 3.1.8 on 2021-08-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Is the Teacher Verified?'),
        ),
    ]
