# Generated by Django 3.1.8 on 2021-04-28 01:36

import accounts.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210427_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=imagekit.models.fields.ProcessedImageField(default='profiles/avatar.png', upload_to=accounts.models.upload_to_path),
        ),
    ]
