# Generated by Django 3.1.8 on 2021-05-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210522_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='user_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Username'),
        ),
    ]
