# Generated by Django 3.1.8 on 2021-12-22 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import teacher_db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='profile_pic',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='profiles/avatar.png', null=True, upload_to=teacher_db.models.Teacher.upload_to_path),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teacher_db', to=settings.AUTH_USER_MODEL, verbose_name='Account'),
        ),
    ]
