# Generated by Django 3.1.8 on 2021-12-22 23:12

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_db', '0002_auto_20211222_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='teacher-one', editable=True, populate_from=['first_name', 'last_name'], unique_with=['first_name', 'last_name'], verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
