# Generated by Django 3.1.8 on 2022-01-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_db', '0003_teacher_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='expected_salary',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Expected salary'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='hour_of_operation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Hour pf operation'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='working_experience',
            field=models.TextField(blank=True, null=True, verbose_name='Working Experience'),
        ),
    ]
