# Generated by Django 3.1.8 on 2021-08-15 05:02

from django.db import migrations, models
import django.utils.timezone
import imagekit.models.fields
import media_lib.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=media_lib.models.upload_to_path)),
                ('file_name', models.CharField(max_length=255, verbose_name='File Name')),
                ('alt_tag', models.CharField(max_length=255, verbose_name='Alt Tag')),
                ('uploaded', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Uploaded At')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['-uploaded'],
            },
        ),
    ]
