# Generated by Django 3.1.8 on 2021-04-28 23:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import imagekit.models.fields
import media_lib.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=media_lib.models.upload_to_path)),
                ('file_name', models.CharField(max_length=255, verbose_name='File Name')),
                ('alt_tag', models.CharField(max_length=255, verbose_name='Alt Tag')),
                ('uploaded', models.DateTimeField(default=datetime.datetime(2021, 4, 28, 23, 49, 15, 103813, tzinfo=utc), verbose_name='Uploaded At')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['-uploaded'],
            },
        ),
    ]
