# Generated by Django 3.1.8 on 2021-04-29 00:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('media_lib', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='uploaded',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Uploaded At'),
        ),
    ]
